// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHq4MgwTm5-r7Tyy2a_crCZgPCg0GGh1Q',
    appId: '1:622563597618:web:1be14bb4a8fedccf118b2b',
    messagingSenderId: '622563597618',
    projectId: 'emotion-e305b',
    authDomain: 'emotion-e305b.firebaseapp.com',
    storageBucket: 'emotion-e305b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW1Y_MYY9678M8bWyNWyiMLZfgAgvyteU',
    appId: '1:622563597618:android:01687ca631cbd86a118b2b',
    messagingSenderId: '622563597618',
    projectId: 'emotion-e305b',
    storageBucket: 'emotion-e305b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8VQy8b1yKhjf5Nx_YO4EoffTHWHfFbAg',
    appId: '1:622563597618:ios:56dc07d19166b9e2118b2b',
    messagingSenderId: '622563597618',
    projectId: 'emotion-e305b',
    storageBucket: 'emotion-e305b.firebasestorage.app',
    iosBundleId: 'com.example.momsBond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8VQy8b1yKhjf5Nx_YO4EoffTHWHfFbAg',
    appId: '1:622563597618:ios:56dc07d19166b9e2118b2b',
    messagingSenderId: '622563597618',
    projectId: 'emotion-e305b',
    storageBucket: 'emotion-e305b.firebasestorage.app',
    iosBundleId: 'com.example.momsBond',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHq4MgwTm5-r7Tyy2a_crCZgPCg0GGh1Q',
    appId: '1:622563597618:web:d4d638d6ce2f2909118b2b',
    messagingSenderId: '622563597618',
    projectId: 'emotion-e305b',
    authDomain: 'emotion-e305b.firebaseapp.com',
    storageBucket: 'emotion-e305b.firebasestorage.app',
  );
}
